### ISSUE TITLE
Example code example_local.py not working 

### ISSUE THREAD

**Issue by darren-uaf** [uafgeotools/rtm#48]
Installed rtm package and attempted to run example_local.py unsuccessfully

Here is the error message I got:
```
(rtm) Darrens-MacBook-Pro:rtm darrentpk$ python3 example_local.py

-------------
DEFINING GRID
-------------
Done
--------------
PROCESSING DEM
--------------
Using external DEM file:
    /Users/darrentpk/opt/anaconda3/envs/rtm/DEM_WGS84.tif
RTMWarning: Elevation units are assumed to be in meters!
Done
Generating DEM hillshade plot...
/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/cartopy/io/srtm.py:272: RuntimeWarning: invalid value encountered in sin
  shaded = np.sin(altitude) * np.sin(slope)\
/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/cartopy/io/srtm.py:273: RuntimeWarning: invalid value encountered in cos
  + np.cos(altitude) * np.cos(slope)\
/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/cartopy/io/srtm.py:274: RuntimeWarning: invalid value encountered in cos
  * np.cos((azimuth - np.pi/2.) - aspect)
Traceback (most recent call last):
  File "example_local.py", line 25, in <module>
    dem = produce_dem(grid, external_file=EXTERNAL_FILE)
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/rtm/grid.py", line 381, in produce_dem
    fig.tight_layout()
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/figure.py", line 2613, in tight_layout
    kwargs = get_tight_layout_figure(
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/tight_layout.py", line 303, in get_tight_layout_figure
    kwargs = auto_adjust_subplotpars(fig, renderer,
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/tight_layout.py", line 84, in auto_adjust_subplotpars
    bb += [ax.get_tightbbox(renderer, for_layout_only=True)]
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 4203, in get_tightbbox
    bbox = a.get_tightbbox(renderer)
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/artist.py", line 286, in get_tightbbox
    bbox = Bbox.intersection(bbox, clip_path.get_extents())
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/matplotlib/path.py", line 603, in get_extents
    return Bbox([xys.min(axis=0), xys.max(axis=0)])
  File "/Users/darrentpk/opt/anaconda3/envs/rtm/lib/python3.8/site-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by liamtoney** [comment]
Hi @darren-uaf, please try out the example now after running a `git pull` to update your local version.

**Comment by darren-uaf** [comment]
Hi @liamtoney, the example works now. Thanks!
