### ISSUE TITLE
Problem with function produce_dem

### ISSUE THREAD

**Issue by SerchVM** [uafgeotools/rtm#81]
Hi,

I am trying to run the example_local.ipynb program.
But, in step dem = produce_dem(grid, external_file=EXTERNAL_FILE)
I get the following error

>>dem = produce_dem(grid, external_file=EXTERNAL_FILE)
--------------
PROCESSING DEM
--------------
Using external DEM file:
	/home/sergio/rtm/DEM_WGS84.tif
ERROR 1: PROJ: proj_as_wkt: DatumEnsemble can only be exported to WKT2:2018
Traceback (most recent call last):
  File "rasterio/_crs.pyx", line 195, in rasterio._crs._CRS.to_wkt
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sergio/rtm/rtm/grid.py", line 268, in produce_dem
    grid_crs = grid.copy().rio.write_crs(proj_target_crs)
  File "/home/sergio/anaconda3/lib/python3.9/site-packages/rioxarray/rioxarray.py", line 498, in write_crs
    grid_map_attrs = pyproj.CRS.from_user_input(data_obj.rio.crs).to_cf()
  File "/home/sergio/anaconda3/lib/python3.9/site-packages/pyproj/crs/crs.py", line 501, in from_user_input
    return cls(value, **kwargs)
  File "/home/sergio/anaconda3/lib/python3.9/site-packages/pyproj/crs/crs.py", line 323, in __init__
    if projparams:
  File "/home/sergio/anaconda3/lib/python3.9/site-packages/rasterio/crs.py", line 83, in __bool__
    return bool(self.wkt)
  File "/home/sergio/anaconda3/lib/python3.9/site-packages/rasterio/crs.py", line 143, in wkt
    self._wkt = self.to_wkt()
  File "/home/sergio/anaconda3/lib/python3.9/site-packages/rasterio/crs.py", line 131, in to_wkt
    return self._crs.to_wkt(morph_to_esri_dialect=morph_to_esri_dialect)
  File "rasterio/_crs.pyx", line 198, in rasterio._crs._CRS.to_wkt
rasterio.errors.CRSError: Cannot convert to WKT. OGR Error code 6

How can i solve the error?
Thank you very much for your help

**Comment by liamtoney** [comment]
Hello, thanks for reporting this issue. I tried that code call in our online Binder (which is Linux) and did not get any errors. That successful call was run on a system with the following package versions:
```
# Name                    Version                   Build  Channel
rasterio                  1.3.6           py310h3e853a9_0    conda-forge
rioxarray                 0.14.1             pyhd8ed1ab_0    conda-forge
pyproj                    3.5.0           py310h15e2413_0    conda-forge
```
What versions are present in your environment?

**Comment by SerchVM** [comment]
Thank you very much for the quick answer.

The problem was the rasterio version, with the help I was able to solve the problem.

Greetings

Sergio Valderrama
